environment:
  DATABASE_URL: "your_database_url"
  API_URL: "your_api_url"
  JWT_SECRET: "your_jwt_secret"
services:
  web:
    image: "your_docker_image_name"
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - API_URL=${API_URL}
      - JWT_SECRET=${JWT_SECRET}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3